version: '3'

services:
  app:
    build:
      context: .
    command: tail -f /dev/null
    volumes:
      - bundler:/usr/local/bundle
      - .:/app
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:8.0.29-oracle
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db:/var/lib/mysql

volumes:
  bundler:
  db:
